LAB 01 [DATE:22.01.2025]

In [9]:
n=int(input("Enter the limit:"))
sum=0
for i in range(0,n+1):
    sum=sum+i
print("Sum: ",sum)
      

Enter the limit: 10


Sum:  45


In [17]:
a=[3,4,6,7,10,22,43]
sum=0
for i in range(len(a)):

    
    sum=sum+a[i]
m=sum/n
print("Sum:",sum)
print("Mean: ",m)

    


Sum: 95
Mean:  13.571428571428571


In [24]:
import numpy as np

a = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])

for i in range(len(a[:, 1])):
    for j in range(len(a[1, :])):
        if a[i][j] % 2 != 0:
            a[i][j] = a[i][j]
        else:
            a[i][j] = 0

print(a)


[[1 0 3 0 5]
 [1 0 3 0 5]
 [1 0 3 0 5]
 [1 0 3 0 5]
 [1 0 3 0 5]]


In [25]:
import numpy as np

a = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])

for i in range(len(a[:, 1])):
    for j in range(len(a[1, :])):
        if j % 2 != 0:
            a[i][j] = a[i][j]
        else:
            a[i][j] = 0

print(a)

[[0 2 0 4 0]
 [0 2 0 4 0]
 [0 2 0 4 0]
 [0 2 0 4 0]
 [0 2 0 4 0]]


In [27]:
import numpy as np

a = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])

for i in range(len(a[:, 1])):
    for j in range(len(a[1, :])):
        if i==j:
            a[i][j] = a[i][j]
        else:
            a[i][j] = 0

print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [52]:
import numpy as np

a = np.array([
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5],
    [1,2,3,4,5]
])

for i in range(len(a[:, 1])):
    for j in range(len(a[1, :])):
        if i==(len(a)-1)-j:
            a[i][j] = a[i][j]
        else:
            a[i][j] = 0

print(a)

[[0 0 0 0 5]
 [0 0 0 4 0]
 [0 0 3 0 0]
 [0 2 0 0 0]
 [1 0 0 0 0]]


scikit-learn
write syntax to load,
train,
test the data,
classifier model functionalities,
classification report!

In [65]:
import numpy as np
a=[32,33,45,67,93,55,63]

if len(a)%2==0:
    index=int((len(a)+1)/2+int(len(a)-1)/2)/2
    median=int(a[index])
else:
    index=int(len(a))/2
    median=int(a[index])
print(median)

TypeError: list indices must be integers or slices, not float